//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplines
    {
        public int discipline_id { get; set; }
        public string discipline_name { get; set; }
        public int hours_total { get; set; }
        public Nullable<int> hours_lecture { get; set; }
        public Nullable<int> hours_practice { get; set; }
        public int semester { get; set; }
        public int specialization_id { get; set; }
    
        public virtual specializations specializations { get; set; }
    }
}
