//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers
    {
        public int teacher_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string patronymic { get; set; }
        public string degree { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
