//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int student_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string patronymic { get; set; }
        public int group_id { get; set; }
        public string record_book_number { get; set; }
        public System.DateTime birth_date { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> enrollment_date { get; set; }
        public Nullable<bool> is_studying { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
